# Generated by Django 2.1.7 on 2019-04-02 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 2, 8, 26, 35, 801659)),
        ),
    ]
